[package]
name = "satori-firmware"
version = "0.1.0"
authors = ["Dan Nixon <dan@dan-nixon.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.66"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
anyhow = "1.0.72"
channel-bridge = { version = "0.3.0", default-features = false, features = ["notification", "embedded-svc"] }
ds18b20 = "0.1.1"
edge-executor = "0.3.0"
embassy-time = "0.1.2"
embedded-hal = "0.2.7"
embedded-svc = { version = "0.25", default-features = false, features = ["alloc", "std"] }
esp-idf-hal = { version = "0.41", default-features = false, features = ["alloc", "std", "edge-executor"]}
esp-idf-svc = { version = "0.46", default-features = false, features = ["alloc", "std", "embassy-time-isr-queue"] }
esp-idf-sys = { version = "0.33", default-features = false, features = ["binstart", "std", "native"] }
heapless = "0.7.16"
koishi-telemetry-protocol = { path = "../../../koishi/telemetry-protocol" }
log = { version = "0.4.17", default-features = false }
one-wire-bus = "0.1.1"
postcard = { version = "1.0.6", features = ["alloc"] }
satori-state = { path = "../state" }
satori-mqtt-config = { path = "../mqtt-config" }
smart-leds = "0.3.0"
thiserror = "1.0.46"
ws2812-esp32-rmt-driver = { version = "0.6.0", default-features = false, features = ["smart-leds-trait"] }

[build-dependencies]
embuild = "0.31.2"
