default: build

build:
    cargo build --release

fmt:
    cargo fmt

check: build
    cargo fmt --check
    cargo clippy -- -Dwarnings

run:
    cargo run --release

attach:
    probe-rs attach --chip RP235x ./target/thumbv8m.main-none-eabihf/release/hoshiguma-rear-sensor-board
