[package]
name = "teeny-rpc-demo-pc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.26"
serde = { version = "1.0.219", features = ["derive"] }
teeny-rpc = { path = "../../" }
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
