[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP235x",
  "--log-format",
  "{L:1} {F:blue}:{l:cyan:1} {s}",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
