OUT_DIR := "./out"

default: (stl "airflow_metering_leak") \
         (stl "alignment_laser_mount") \
         (stl "coolant_filter_mount") \
         (dxf "cooler_connector_blank") \
         (dxf "cooler_connector_rj45") \
         (dxf "front_panel") \
         (dxf "manual_focus_tool") \
         (dxf "rear_connector_panel") \
         (stl "rear_sensor_board_case/box") \
         (dxf "rear_sensor_board_case/lid") \
         (stl "side_connector_blanking_plate")

dxf FILE:
    mkdir -p $(dirname {{OUT_DIR}}/{{FILE}}.dxf)
    openscad -o {{OUT_DIR}}/{{FILE}}.dxf {{FILE}}.scad

stl FILE:
    mkdir -p $(dirname {{OUT_DIR}}/{{FILE}}.dxf)
    openscad -o {{OUT_DIR}}/{{FILE}}.stl {{FILE}}.scad

clean:
    rm -rf {{OUT_DIR}}
