OUT_DIR := "./out"

default: (stl "airflow_metering_leak") \
         (stl "alignment_laser_mount") \
         (stl "coolant_filter_mount") \
         (dxf "cooler_connector_blanking_plate") \
         (dxf "front_panel") \
         (dxf "manual_focus_tool") \
         (dxf "rear_connector_panel") \
         (stl "side_connector_blanking_plate")

dxf FILE:
    mkdir -p {{OUT_DIR}}
    openscad -o {{OUT_DIR}}/{{FILE}}.dxf {{FILE}}.scad

stl FILE:
    mkdir -p {{OUT_DIR}}
    openscad -o {{OUT_DIR}}/{{FILE}}.stl {{FILE}}.scad

clean:
    rm -rf {{OUT_DIR}}
