[package]
name = "hoshiguma-diagnostic-cli"
version = "0.1.0"
authors = ["Dan Nixon <dan@dan-nixon.com>"]
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.3.18", features = ["derive"] }
git-version = "0.3.5"
hoshiguma-protocol = { path = "../protocol" }
teeny-rpc = { path = "../teeny-rpc" }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "time"] }

[lints.rust]
unused_crate_dependencies = "deny"
