[package]
name = "koishi-telemetry-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
enumset = { version = "1.1.3", features = ["serde"] }
postcard = { version = "1.0.6", default-features = false, features = ["use-std"] }
serde = { version = "1.0.174", features = ["derive"] }
