---
name: Koishi

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting-firmware:
    name: Formatting (firmware)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./koishi/firmware

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Format
        run: nix develop --command cargo fmt -- --check

      - name: Clippy
        run: nix develop --command cargo clippy -- -Dwarnings

  formatting-firmware-tests:
    name: Formatting (firmware tests)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./koishi/firmware-tests

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Format
        run: nix develop --command cargo fmt -- --check

      - name: Clippy
        run: nix develop --command cargo clippy -- -Dwarnings

  formatting-postcard-data-receiver:
    name: Formatting (postcard-data-receiver)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./koishi/postcard-data-receiver

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Format
        run: nix develop --command cargo fmt -- --check

      - name: Clippy
        run: nix develop --command cargo clippy -- -Dwarnings

  build-and-test-firmware:
    name: Build and Test (firmware)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Build
        working-directory: ./koishi/firmware
        run: |
          # Build as intended for hardware first
          nix develop --command cargo build --release
          nix develop --command cargo build --release --features reporting_debug
          nix develop --command cargo build --release --features reporting_postcard
          # Build for simulator tests
          nix develop --command cargo build --release --features simulator

      - name: In Simulator Tests
        working-directory: ./koishi/firmware-tests
        run: nix develop --command cargo test

  build-and-test-postcard-data-receiver:
    name: Build and Test (postcard-data-receiver)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Build
        working-directory: ./koishi/firmware
        run: nix develop --command cargo build
