---
name: Koishi

on:
  push:
    branches:
      - main
    paths:
      - 'flake.*'
      - 'koishi/**'
  pull_request:
    paths:
      - 'flake.*'
      - 'koishi/**'

jobs:
  formatting-firmware:
    name: Formatting (firmware)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./koishi/firmware

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27

      - name: Clippy
        run: nix develop --command cargo clippy -- -Dwarnings

  build-and-test-firmware:
    name: Build and Test (firmware)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27

      - name: Build
        working-directory: ./koishi/firmware
        run: |
          nix develop --command cargo build --release
          nix develop --command cargo build --release --features telemetry
