---
name: Satori

on:
  push:
    branches:
      - main
    paths:
      - 'flake.*'
      - 'satori/**'
  pull_request:
    paths:
      - 'flake.*'
      - 'satori/**'

jobs:
  formatting-firmware:
    name: Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./satori/firmware

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - run: rustup target add thumbv6m-none-eabi

      - name: Clippy
        run: nix develop --command cargo clippy -- -Dwarnings

  build-and-test-firmware:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - run: rustup target add thumbv6m-none-eabi

      - name: Build
        working-directory: ./satori/firmware
        run: |
          nix develop --command cargo build --release
          nix develop --command cargo build --release --features panic-probe
