---
name: teeny-rpc

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/teeny-rpc.yml'
      - 'devenv.*'
      - 'teeny-rpc/**'
  pull_request:
    paths:
      - '.github/workflows/teeny-rpc.yml'
      - 'devenv.*'
      - 'teeny-rpc/**'

jobs:
  library:
    name: Library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./teeny-rpc
          rustup show
          cargo clippy -- -Dwarnings
          cargo clippy --no-default-features -F no-std -- -Dwarnings

      - name: Tests
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./teeny-rpc
          rustup show
          cargo test

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./teeny-rpc
          rustup show
          cargo build
          cargo build --no-default-features -F no-std

  example-pc:
    name: PC example
    runs-on: ubuntu-latest
    needs:
      - library

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./teeny-rpc/examples/pc
          rustup show
          cargo build --release

  example-pi-pico:
    name: Pi Pico example
    runs-on: ubuntu-latest
    needs:
      - library

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./teeny-rpc/examples/pi-pico
          rustup target add thumbv6m-none-eabi
          rustup show
          cargo build --release
