---
name: Peripheral Controller Telemetry Receiver

on:
  push:
    branches:
      - main
    paths:
      - 'flake.*'
      - 'peripheral-controller/telemetry-protocol/**'
      - 'peripheral-controller/telemetry-receiver/**'
  pull_request:
    paths:
      - 'flake.*'
      - 'peripheral-controller/telemetry-protocol/**'
      - 'peripheral-controller/telemetry-receiver/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./peripheral-controller/telemetry-receiver

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Clippy
        run: |
          eval "$(nix print-dev-env)"
          set +x

          rustup show

          cargo clippy -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    defaults:
      run:
        working-directory: ./peripheral-controller/telemetry-receiver

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Build
        run: |
          eval "$(nix print-dev-env)"
          set +x

          rustup show

          cargo build --release
