---
name: Peripheral Controller Telemetry Receiver

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/telemetry-receiver.yml'
      - 'devenv.*'
      - 'telemetry-protocol/**'
      - 'telemetry-receiver/**'
  pull_request:
    paths:
      - '.github/workflows/telemetry-receiver.yml'
      - 'devenv.*'
      - 'telemetry-protocol/**'
      - 'telemetry-receiver/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: |
          set -x

          cd ./telemetry-receiver

          rustup show

          cargo clippy -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x

          cd ./telemetry-receiver

          rustup show

          cargo build --release
